---
title: "Assignment 3 ggplot2"
author:
- familyname: Li
  othernames: Siyi
  address: Monash Universty
  email: "slii0048@student.monash.edu"
  correspondingauthor: true
  qualifications: 29018102
- familyname: Wang
  othernames: Yusen
  address: Monash Universty
  email: "ywa136@student.monash.edu"
  correspondingauthor: true
  qualifications: 27496538
- familyname: Tsakis
  othernames: Alexi
  address: Monash Universty
  email: "atsa0003@student.monash.edu"
  correspondingauthor: true
  qualifications: 29682525
department: Our consultancy \newline Alexi  &\newline Siyi  &\newline Yusen
organization: Australian Government
bibliography: references.bib
biblio-style: authoryear-comp
linestretch: 1.5
output:
  bookdown::pdf_document2:
    latex_engine: lualatex
    template: monashreport2.tex
    fig_caption: yes
    fig_height: 5
    fig_width: 8
    includes:
    in_header: preamble.tex
    keep_tex: yes
    number_sections: yes
    citation_package: biblatex
    toc: false
---

```{r , echo = FALSE, include=FALSE, message = FALSE, warning = FALSE}
# Libraries
set.seed(96024)

library(tidyverse)
library(readr)
library(kableExtra)
library(bookdown)
```

```{r, echo = FALSE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(fig.pos = 'H', echo = FALSE, message = FALSE, warning = FALSE)
```

{Section 1}

####Compulsory Seatbelts 1983

```{r, echo = FALSE, message = FALSE, warning = FALSE}
Seatbelts_data = data.frame(as.matrix(Seatbelts),date=time(Seatbelts))
```

```{r DriversKilled, fig.cap = "Drivers killed in accidents over time", echo = FALSE, message = FALSE, warning = FALSE}
ggplot(data=Seatbelts_data, aes(x=date,y=DriversKilled,col=law))+geom_line()+geom_smooth()
```

```{r FrontKilled, fig.cap = "Frontseat passengers killed in accidents over time", echo = FALSE, message = FALSE, warning = FALSE}
ggplot(data=Seatbelts_data, aes(x=date,y=front,col=law))+geom_line()+geom_smooth()
```

```{r RearKilled, fig.cap = "Backseat passengers killed in accidents over time", echo = FALSE, message = FALSE, warning = FALSE}
ggplot(data=Seatbelts_data, aes(x=date,y=rear,col=law))+geom_line()+geom_smooth()
```

```{r VanKilled, fig.cap = "Light goods vehicle drivers killed in accidents over time", echo = FALSE, message = FALSE, warning = FALSE}
ggplot(data=Seatbelts_data, aes(x=date,y=VanKilled,col=law))+geom_line()+geom_smooth()
```

```{r DriverTable, echo = FALSE, message = FALSE, warning = FALSE}
Seatbelts_data %>%
  group_by(law) %>%
  summarise(DriversKilled_Average=mean(DriversKilled)) 
```

```{r RearTable, echo = FALSE, message = FALSE, warning = FALSE}
Seatbelts_data %>%
  group_by(law) %>%
  summarise(Rear_Average=mean(rear)) 
```

```{r FrontTable, echo = FALSE, message = FALSE, warning = FALSE}
Seatbelts_data %>%
  group_by(law) %>%
  summarise(Front_Average=mean(front)) 
```

```{r VanTable, echo = FALSE, message = FALSE, warning = FALSE}
Seatbelts_data %>%
  group_by(law) %>%
  summarise(Van_Average=mean(VanKilled)) 
```



{Section 2}

{Section 3}
